# coding: utf-8

# flake8: noqa

"""
    API Аутентификации

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.1.1
    Generated by: https://openapi-generator.tech
"""

__version__ = "v1.1.1"

# import ApiClient
from beget_openapi_auth.api_client import ApiClient

# import Configuration
from beget_openapi_auth.configuration import Configuration

# import exceptions
from beget_openapi_auth.exceptions import OpenApiException
from beget_openapi_auth.exceptions import ApiAttributeError
from beget_openapi_auth.exceptions import ApiTypeError
from beget_openapi_auth.exceptions import ApiValueError
from beget_openapi_auth.exceptions import ApiKeyError
from beget_openapi_auth.exceptions import ApiException
