# coding: utf-8

"""
    API Аутентификации

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.1.2
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_auth
from beget_openapi_auth.model.auth_refresh_token_response import AuthRefreshTokenResponse
from beget_openapi_auth import configuration


class TestAuthRefreshTokenResponse(unittest.TestCase):
    """AuthRefreshTokenResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
