# coding: utf-8

"""
    API Аутентификации

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.1.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_auth import schemas  # noqa: F401


class AuthSwitchUserResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            token = schemas.StrSchema
            
            
            class error(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'enum'
                    enum_value_to_name = {
                        "INTERNAL_ERROR": "INTERNAL_ERROR",
                        "EMPTY_TARGET_LOGIN": "EMPTY_TARGET_LOGIN",
                        "TARGET_FORBIDDEN": "TARGET_FORBIDDEN",
                        "TARGET_NOT_FOUND": "TARGET_NOT_FOUND",
                        "TARGET_PASSWORD_REQUIRED": "TARGET_PASSWORD_REQUIRED",
                        "TARGET_CODE_REQUIRED": "TARGET_CODE_REQUIRED",
                        "TARGET_INCORRECT_CODE": "TARGET_INCORRECT_CODE",
                        "SENT_LIMIT_REACHED": "SENT_LIMIT_REACHED",
                        "INPUT_LIMIT_REACHED": "INPUT_LIMIT_REACHED",
                        "TARGET_ON_MAINTENANCE": "TARGET_ON_MAINTENANCE",
                        "TARGET_DELETED": "TARGET_DELETED",
                        "TOKEN_REVOKED": "TOKEN_REVOKED",
                        "CODE_REQUIRED_EMAIL": "CODE_REQUIRED_EMAIL",
                        "CODE_REQUIRED_SMS": "CODE_REQUIRED_SMS",
                        "IP_BLOCKED": "IP_BLOCKED",
                    }
                
                @schemas.classproperty
                def INTERNAL_ERROR(cls):
                    return cls("INTERNAL_ERROR")
                
                @schemas.classproperty
                def EMPTY_TARGET_LOGIN(cls):
                    return cls("EMPTY_TARGET_LOGIN")
                
                @schemas.classproperty
                def TARGET_FORBIDDEN(cls):
                    return cls("TARGET_FORBIDDEN")
                
                @schemas.classproperty
                def TARGET_NOT_FOUND(cls):
                    return cls("TARGET_NOT_FOUND")
                
                @schemas.classproperty
                def TARGET_PASSWORD_REQUIRED(cls):
                    return cls("TARGET_PASSWORD_REQUIRED")
                
                @schemas.classproperty
                def TARGET_CODE_REQUIRED(cls):
                    return cls("TARGET_CODE_REQUIRED")
                
                @schemas.classproperty
                def TARGET_INCORRECT_CODE(cls):
                    return cls("TARGET_INCORRECT_CODE")
                
                @schemas.classproperty
                def SENT_LIMIT_REACHED(cls):
                    return cls("SENT_LIMIT_REACHED")
                
                @schemas.classproperty
                def INPUT_LIMIT_REACHED(cls):
                    return cls("INPUT_LIMIT_REACHED")
                
                @schemas.classproperty
                def TARGET_ON_MAINTENANCE(cls):
                    return cls("TARGET_ON_MAINTENANCE")
                
                @schemas.classproperty
                def TARGET_DELETED(cls):
                    return cls("TARGET_DELETED")
                
                @schemas.classproperty
                def TOKEN_REVOKED(cls):
                    return cls("TOKEN_REVOKED")
                
                @schemas.classproperty
                def CODE_REQUIRED_EMAIL(cls):
                    return cls("CODE_REQUIRED_EMAIL")
                
                @schemas.classproperty
                def CODE_REQUIRED_SMS(cls):
                    return cls("CODE_REQUIRED_SMS")
                
                @schemas.classproperty
                def IP_BLOCKED(cls):
                    return cls("IP_BLOCKED")
            __annotations__ = {
                "token": token,
                "error": error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> MetaOapg.properties.error: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["token", "error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["token"]) -> typing.Union[MetaOapg.properties.token, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> typing.Union[MetaOapg.properties.error, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["token", "error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        token: typing.Union[MetaOapg.properties.token, str, schemas.Unset] = schemas.unset,
        error: typing.Union[MetaOapg.properties.error, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AuthSwitchUserResponse':
        return super().__new__(
            cls,
            *args,
            token=token,
            error=error,
            _configuration=_configuration,
            **kwargs,
        )
